<a href="https://colab.research.google.com/github/PhuongUyen-tt/blank-app/blob/main/Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: kết nối đến driver

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# prompt: đọc dữ liệu từ đường dẫn /content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /data.csv

import pandas as pd

file_path = '/content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /data.csv'
df = pd.read_csv(file_path)
print(df.head())

   transaction_id     transaction_date transaction_time  store_id  \
0            1567  2023-03-19 00:00:00         20:30:42       501
1            1568  2022-07-14 00:00:00         22:59:16       302
2            1569  2023-05-03 00:00:00         15:31:33       201
3            1570  2025-04-11 00:00:00         15:30:54       202
4            1571  2024-02-20 00:00:00         09:25:54       401

            store_location  product_id  transaction_qty  unit_price  \
0  Nha Trang - City Center           7                2       45000
1      Da Nang - Thanh Khe           1                1       29000
2        Hanoi - Hoan Kiem          24                4       35000
3          Hanoi - Ba Dinh          15                5       55000
4        Hue - City Center           3                2       29000

   Total_Bill    product_category product_type    product_detail     Size  \
0       90000                 Tea          Tea      Tra Sen Vang        M
1       29000  Traditional Coffee       Coffee       Phin Sua Da        M
2      140000                Food      Banh Mi    Banh Mi Ga Que  Regular
3      275000              Freeze       Freeze  Freeze Chocolate        M
4       58000  Traditional Coffee       Coffee       Phin Den Da        M

   customer_id   customer_name  Gender  Age           Occupation Season  \
0         9143     Lý Anh Xuân    Male   68           Nghề tự do   Xuân
1         1935    Mai Thanh An  Female   80           Nghề tự do     Hè
2         7189          Lê Yến    Male   24  Sinh viên, học sinh   Xuân
3          246     Lý Thị Xuân    Male   22  Sinh viên, học sinh   Xuân
4         8704  Bùi Anh Phương  Female   23  Sinh viên, học sinh   Đông

    Income
0  7000000
1  7000000
2  3000000
3  3000000
4  3000000

In [3]:
# prompt: chia bộ dữ liệu thành 2 phần là tập train và tập test

from sklearn.model_selection import train_test_split

# Assuming 'df' is your DataFrame loaded from data.csv
# Assuming 'target_column' is the name of your target variable column
# If you don't have a target variable, you can split the entire DataFrame

# Example if you have a target column
# X = df.drop('target_column', axis=1) # Features
# y = df['target_column'] # Target variable
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split with 20% for testing

# Example if you are splitting the entire DataFrame
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42) # Split with 20% for testing

print("Training set shape:", train_df.shape)
print("Testing set shape:", test_df.shape)

Training set shape: (24000, 20)
Testing set shape: (6000, 20)

In [4]:
# prompt: mô tả kích thước và kiểu dữ liệu của tập train và tập test

# Print the shape and data types of the training set
print("\nTraining set information:")
print(train_df.info())

# Print the shape and data types of the testing set
print("\nTesting set information:")
print(test_df.info())

Training set information:
<class 'pandas.core.frame.DataFrame'>
Index: 24000 entries, 21753 to 23654
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    24000 non-null  int64
 1   transaction_date  24000 non-null  object
 2   transaction_time  24000 non-null  object
 3   store_id          24000 non-null  int64
 4   store_location    24000 non-null  object
 5   product_id        24000 non-null  int64
 6   transaction_qty   24000 non-null  int64
 7   unit_price        24000 non-null  int64
 8   Total_Bill        24000 non-null  int64
 9   product_category  24000 non-null  object
 10  product_type      24000 non-null  object
 11  product_detail    24000 non-null  object
 12  Size              24000 non-null  object
 13  customer_id       24000 non-null  int64
 14  customer_name     24000 non-null  object
 15  Gender            24000 non-null  object
 16  Age               24000 non-null  int64
 17  Occupation        24000 non-null  object
 18  Season            24000 non-null  object
 19  Income            24000 non-null  int64
dtypes: int64(9), object(11)
memory usage: 3.8+ MB
None

Testing set information:
<class 'pandas.core.frame.DataFrame'>
Index: 6000 entries, 2308 to 29171
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    6000 non-null   int64
 1   transaction_date  6000 non-null   object
 2   transaction_time  6000 non-null   object
 3   store_id          6000 non-null   int64
 4   store_location    6000 non-null   object
 5   product_id        6000 non-null   int64
 6   transaction_qty   6000 non-null   int64
 7   unit_price        6000 non-null   int64
 8   Total_Bill        6000 non-null   int64
 9   product_category  6000 non-null   object
 10  product_type      6000 non-null   object
 11  product_detail    6000 non-null   object
 12  Size              6000 non-null   object
 13  customer_id       6000 non-null   int64
 14  customer_name     6000 non-null   object
 15  Gender            6000 non-null   object
 16  Age               6000 non-null   int64
 17  Occupation        6000 non-null   object
 18  Season            6000 non-null   object
 19  Income            6000 non-null   int64
dtypes: int64(9), object(11)
memory usage: 984.4+ KB
None

In [5]:
# prompt: liệt kê các cột có định dạng không phải kiểu số

# List columns that are not of numeric type
non_numeric_cols = df.select_dtypes(exclude=['number']).columns

print("\nColumns with non-numeric data types:")
print(list(non_numeric_cols))

Columns with non-numeric data types:
['transaction_date', 'transaction_time', 'store_location', 'product_category', 'product_type', 'product_detail', 'Size', 'customer_name', 'Gender', 'Occupation', 'Season']

In [6]:
# Đổi dữ liệu từ dạng định danh (object) về dạng số
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()

# Biến đổi tập train
train_df["transaction_date"] = lb_make.fit_transform(train_df["transaction_date"])
train_df["transaction_time"] = lb_make.fit_transform(train_df["transaction_time"])
train_df["store_location"] = lb_make.fit_transform(train_df["store_location"])
train_df["product_category"] = lb_make.fit_transform(train_df["product_category"])
train_df["product_type"] = lb_make.fit_transform(train_df["product_type"])
train_df["product_detail"] = lb_make.fit_transform(train_df["product_detail"])
train_df["Size"] = lb_make.fit_transform(train_df["Size"])
train_df["customer_name"] = lb_make.fit_transform(train_df["customer_name"])
train_df["Gender"] = lb_make.fit_transform(train_df["Gender"])
train_df["Occupation"] = lb_make.fit_transform(train_df["Occupation"])
train_df["Season"] = lb_make.fit_transform(train_df["Season"])

# Biến đổi tập test
test_df["transaction_date"] = lb_make.fit_transform(test_df["transaction_date"])
test_df["transaction_time"] = lb_make.fit_transform(test_df["transaction_time"])
test_df["store_location"] = lb_make.fit_transform(test_df["store_location"])
test_df["product_category"] = lb_make.fit_transform(test_df["product_category"])
test_df["product_type"] = lb_make.fit_transform(test_df["product_type"])
test_df["product_detail"] = lb_make.fit_transform(test_df["product_detail"])
test_df["Size"] = lb_make.fit_transform(test_df["Size"])
test_df["customer_name"] = lb_make.fit_transform(test_df["customer_name"])
test_df["Gender"] = lb_make.fit_transform(test_df["Gender"])
test_df["Occupation"] = lb_make.fit_transform(test_df["Occupation"])
test_df["Season"] = lb_make.fit_transform(test_df["Season"])

# Xem thử 10 dòng đầu tiên sau khi biến đổi
train_df.head(10)

,transaction_id,transaction_date,transaction_time,store_id,store_location,product_id,transaction_qty,unit_price,Total_Bill,product_category,product_type,product_detail,Size,customer_id,customer_name,Gender,Age,Occupation,Season,Income
21753,23320,873,1453,401,10,6,1,41000,41000,4,2,1,0,3195,89,0,18,14,1,8000000
251,1818,729,5899,601,0,10,4,51000,204000,3,6,17,0,1590,3088,0,17,7,2,15000000
22941,24508,114,3801,201,5,25,2,35000,70000,1,0,5,2,4130,2008,1,55,8,0,7000000
618,2185,665,18438,401,10,22,1,61000,61000,0,2,7,0,1456,517,1,45,4,3,8000000
17090,18657,314,11754,102,7,9,4,45000,180000,3,6,17,1,4813,3776,1,29,11,2,10000000
6362,7929,827,2319,601,0,9,5,45000,225000,3,6,17,1,6389,3406,1,43,2,0,8000000
24680,26247,35,15892,101,6,8,3,51000,153000,3,6,18,0,4867,929,0,75,9,0,8000000
28329,29896,960,893,501,11,26,4,29000,116000,1,5,6,2,2946,645,1,13,13,3,3000000
15874,17441,1030,7663,102,7,29,4,25000,100000,1,3,8,2,7096,4037,1,28,11,3,10000000
22653,24220,460,13334,201,5,9,3,45000,135000,3,6,17,1,9742,3532,1,74,4,0,8000000

In [7]:
# prompt: liệt kê các cột của bộ dữ liệu

print("Columns of the dataframe:")
df.columns

Columns of the dataframe:

Index(['transaction_id', 'transaction_date', 'transaction_time', 'store_id',
       'store_location', 'product_id', 'transaction_qty', 'unit_price',
       'Total_Bill', 'product_category', 'product_type', 'product_detail',
       'Size', 'customer_id', 'customer_name', 'Gender', 'Age', 'Occupation',
       'Season', 'Income'],
      dtype='object')

In [8]:
# Xác định các thuộc tính độc lập và thuộc tính phụ thuộc
features = ['store_location', 'transaction_qty','Size',
            'Total_Bill','Gender','Age','Season']

target = ['product_category', 'product_detail']

X_train = train_df[features]
y_train = train_df[target]
X_test = test_df[features]
y_test = test_df[target]

print(y_train.head())

       product_category  product_detail
21753                 4               1
251                   3              17
22941                 1               5
618                   0               7
17090                 3              17

In [9]:
# prompt: xây dựng mô hình Gradient Boosting Classifier cho máy học

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize the base Gradient Boosting Classifier
# You can tune parameters like n_estimators, learning_rate, max_depth, etc.
gb_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Use MultiOutputClassifier to handle multiple target variables
multioutput_gb_classifier = MultiOutputClassifier(gb_classifier, n_jobs=-1)

# Train the model
multioutput_gb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = multioutput_gb_classifier.predict(X_test)

# Evaluate the model for each target variable
print("Evaluation Results:")
for i, col in enumerate(target):
    print(f"\nResults for target variable: {col}")
    print("Accuracy:", accuracy_score(y_test[col], y_pred[:, i]))
    print("Classification Report:\n", classification_report(y_test[col], y_pred[:, i]))

Evaluation Results:

Results for target variable: product_category
Accuracy: 0.7966666666666666
Classification Report:
               precision    recall  f1-score   support

           0       0.57      0.48      0.52      1381
           1       1.00      1.00      1.00      1396
           2       0.70      0.58      0.64      1199
           3       0.66      1.00      0.79       813
           4       1.00      1.00      1.00      1211

    accuracy                           0.80      6000
   macro avg       0.79      0.81      0.79      6000
weighted avg       0.80      0.80      0.79      6000


Results for target variable: product_detail
Accuracy: 0.5383333333333333
Classification Report:
               precision    recall  f1-score   support

           0       0.32      0.20      0.25       424
           1       1.00      1.00      1.00       424
           2       1.00      1.00      1.00       206
           3       1.00      1.00      1.00       197
           4       0.57      0.26      0.36       215
           5       0.51      0.79      0.62       209
           6       1.00      1.00      1.00       207
           7       0.26      0.37      0.31       396
           8       0.48      0.70      0.57       181
           9       0.46      0.26      0.33       181
          10       1.00      1.00      1.00       204
          11       1.00      1.00      1.00       418
          12       0.25      0.25      0.25       382
          13       0.26      0.13      0.17       399
          14       0.24      0.27      0.26       357
          15       0.49      0.53      0.51       409
          16       0.45      0.41      0.43       378
          17       0.35      0.43      0.39       404
          18       0.33      0.39      0.36       409

    accuracy                           0.54      6000
   macro avg       0.58      0.58      0.57      6000
weighted avg       0.54      0.54      0.53      6000

In [12]:
# prompt: So sánh hiệu suất của  mô hình trên tập train và tập test và chỉ ra mô hình có fit thế nào

# Dự đoán trên tập huấn luyện để so sánh hiệu suất
y_train_pred = multioutput_gb_classifier.predict(X_train)

# So sánh hiệu suất trên tập train và test cho từng biến mục tiêu
print("\nComparison of Performance on Train and Test Sets:")
for i, col in enumerate(target):
    print(f"\nPerformance for target variable: {col}")

    # Tính toán độ chính xác trên tập huấn luyện
    train_accuracy = accuracy_score(y_train[col], y_train_pred[:, i])
    print(f"Train Accuracy: {train_accuracy:.4f}")

    # Tính toán độ chính xác trên tập kiểm tra
    test_accuracy = accuracy_score(y_test[col], y_pred[:, i])
    print(f"Test Accuracy: {test_accuracy:.4f}")

    # Phân tích kết quả để nhận xét về mô hình
    if train_accuracy > test_accuracy + 0.05: # Ngưỡng chênh lệch có thể điều chỉnh
        print(f"  -> Mô hình có dấu hiệu overfitting trên biến '{col}'.")
        print(f"     Độ chính xác trên tập huấn luyện cao hơn đáng kể so với tập kiểm tra.")
    elif test_accuracy > train_accuracy + 0.05:
        print(f"  -> Mô hình có thể bị underfitting hoặc cần thêm dữ liệu/đặc trưng tốt hơn cho biến '{col}'.")
        print(f"     Độ chính xác trên tập kiểm tra cao hơn tập huấn luyện (ít xảy ra với mô hình phức tạp).")
    else:
        print(f"  -> Hiệu suất của mô hình tương đối ổn định giữa tập huấn luyện và kiểm tra cho biến '{col}'.")
        print(f"     Mô hình có vẻ fit tốt trên cả hai tập.")

# Nhận xét chung về mô hình dựa trên kết quả tổng thể
print("\nOverall Model Fit Assessment:")
avg_train_accuracy = sum(accuracy_score(y_train[col], y_train_pred[:, i]) for i, col in enumerate(target)) / len(target)
avg_test_accuracy = sum(accuracy_score(y_test[col], y_pred[:, i]) for i, col in enumerate(target)) / len(target)

print(f"Average Train Accuracy across targets: {avg_train_accuracy:.4f}")
print(f"Average Test Accuracy across targets: {avg_test_accuracy:.4f}")

if avg_train_accuracy > avg_test_accuracy + 0.05:
    print("  -> Overall, the model shows signs of overfitting.")
elif avg_test_accuracy > avg_train_accuracy + 0.05:
     print("  -> Overall, the model might be underfitting or needs improvement.")
else:
    print("  -> Overall, the model seems to have a reasonable fit, with similar performance on training and testing data.")

print("\nInterpretation of Classification Reports:")
print("Examine the precision, recall, and f1-score for each class in the classification reports printed above.")
print("High precision means fewer false positives.")
print("High recall means fewer false negatives.")
print("The f1-score is the harmonic mean of precision and recall.")
print("These metrics provide a more detailed view of the model's performance for each category.")
print("Look for significant differences in performance across different product categories and details.")

Comparison of Performance on Train and Test Sets:

Performance for target variable: product_category
Train Accuracy: 0.8167
Test Accuracy: 0.7967
  -> Hiệu suất của mô hình tương đối ổn định giữa tập huấn luyện và kiểm tra cho biến 'product_category'.
     Mô hình có vẻ fit tốt trên cả hai tập.

Performance for target variable: product_detail
Train Accuracy: 0.5855
Test Accuracy: 0.5383
  -> Hiệu suất của mô hình tương đối ổn định giữa tập huấn luyện và kiểm tra cho biến 'product_detail'.
     Mô hình có vẻ fit tốt trên cả hai tập.

Overall Model Fit Assessment:
Average Train Accuracy across targets: 0.7011
Average Test Accuracy across targets: 0.6675
  -> Overall, the model seems to have a reasonable fit, with similar performance on training and testing data.

Interpretation of Classification Reports:
Examine the precision, recall, and f1-score for each class in the classification reports printed above.
High precision means fewer false positives.
High recall means fewer false negatives.
The f1-score is the harmonic mean of precision and recall.
These metrics provide a more detailed view of the model's performance for each category.
Look for significant differences in performance across different product categories and details.

In [13]:
# prompt: sử dụng mô hình dự báo "product_category" và "product_detail" với dữ liệu khách hàng mới

# Create a sample new customer DataFrame (replace with your actual new customer data)
# Make sure the column names and data types match the features used for training
new_customer_data = {
    'store_location': ['Location A'],  # Example location
    'transaction_qty': [1],
    'Size': ['M'],
    'Total_Bill': [150000], # Example bill
    'Gender': ['Male'],
    'Age': [30],
    'Season': ['Summer']
}
new_customer_df = pd.DataFrame(new_customer_data)
print(new_customer_df.head())
# Apply the same LabelEncoding to the new customer data
# It's important to use the *same* LabelEncoder fitted on the training data
# To do this robustly, you would typically save the fitted LabelEncoders
# Here, for demonstration, we'll re-fit (which might not be ideal if new categories appear)
# A better approach is to use the LabelEncoders fitted on the combined data before splitting
# or saving and loading the fitted encoders.

# For demonstration purposes, let's assume we have access to the original combined data's fitted encoders
# In a real-world scenario, you would save and load these
# For now, let's simulate applying the transformations based on the columns
# This assumes the new customer data categories are present in the training data

# Apply the same label encoding transformations as done on the training data
# Define the columns that were label encoded
cols_to_encode = ["store_location", "Size", "Gender", "Season"]

# Create a dictionary to store LabelEncoders (in a real scenario, load them)
# Here, we refit for simplicity, but be cautious with new categories
fitted_encoders = {}
for col in cols_to_encode:
    # Fit on the combined training and new data to handle potential new categories
    # Or better, fit on the original full df before splitting
    combined_data = pd.concat([train_df[col], new_customer_df[col]], axis=0).astype(str)
    lb = LabelEncoder()
    lb.fit(combined_data)
    fitted_encoders[col] = lb
    new_customer_df[col] = fitted_encoders[col].transform(new_customer_df[col].astype(str))

# Ensure the feature columns match exactly
new_customer_X = new_customer_df[features]

# Predict product category and product detail for the new customer
new_customer_prediction = multioutput_gb_classifier.predict(new_customer_X)

# The prediction is in the encoded format. We need to inverse transform it
# To do this, we need the inverse transform functionality of the LabelEncoders
# fitted on the target variables ('product_category', 'product_detail') from the training data.

# We need the original LabelEncoders that were used to encode 'product_category' and 'product_detail'
# when preparing the y_train data.
# Let's simulate getting those inverse transformers.
# In a real application, you would save and load these fitted transformers.

# For demonstration, let's assume we can access the inverse transform based on the unique values
# seen during training. This is a workaround and less robust than saving/loading encoders.
# We need the original unique values to map back.

# Get the inverse transformation for 'product_category'
# Create a temporary encoder fitted on the original 'product_category' values from df
temp_cat_encoder = LabelEncoder()
temp_cat_encoder.fit(df['product_category'])
predicted_product_category_encoded = new_customer_prediction[:, 0]
predicted_product_category = temp_cat_encoder.inverse_transform(predicted_product_category_encoded)

# Get the inverse transformation for 'product_detail'
# Create a temporary encoder fitted on the original 'product_detail' values from df
temp_detail_encoder = LabelEncoder()
temp_detail_encoder.fit(df['product_detail'])
predicted_product_detail_encoded = new_customer_prediction[:, 1]
predicted_product_detail = temp_detail_encoder.inverse_transform(predicted_product_detail_encoded)


print("\nPrediction for the new customer:")
print("Predicted Product Category:", predicted_product_category[0])
print("Predicted Product Detail:", predicted_product_detail[0])

  store_location  transaction_qty Size  Total_Bill Gender  Age  Season
0     Location A                1    M      150000   Male   30  Summer

Prediction for the new customer:
Predicted Product Category: Food
Predicted Product Detail: Banh Bong Lan Trung Muoi

In [14]:
# prompt: lưu mô hình

import joblib

# Define the path to save the model
model_save_path = '/content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /multioutput_gb_model.pkl'

# Save the trained model
joblib.dump(multioutput_gb_classifier, model_save_path)

print(f"Model saved successfully at: {model_save_path}")

# You might also want to save the fitted LabelEncoders for the target variables
# This allows you to correctly inverse transform predictions later without needing the original df

# Save the encoder for 'product_category'
cat_encoder_save_path = '/content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /product_category_encoder.pkl'
joblib.dump(temp_cat_encoder, cat_encoder_save_path) # Use the encoder fitted on original df

# Save the encoder for 'product_detail'
detail_encoder_save_path = '/content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /product_detail_encoder.pkl'
joblib.dump(temp_detail_encoder, detail_encoder_save_path) # Use the encoder fitted on original df

print(f"Product category encoder saved at: {cat_encoder_save_path}")
print(f"Product detail encoder saved at: {detail_encoder_save_path}")

# Optionally, save the encoders used for the feature columns as well,
# if you need to encode new input data in a separate script/environment
feature_encoders_save_path = '/content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /feature_encoders.pkl'
joblib.dump(fitted_encoders, feature_encoders_save_path)
print(f"Feature encoders saved at: {feature_encoders_save_path}")

Model saved successfully at: /content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /multioutput_gb_model.pkl
Product category encoder saved at: /content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /product_category_encoder.pkl
Product detail encoder saved at: /content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /product_detail_encoder.pkl
Feature encoders saved at: /content/drive/MyDrive/HK II | 24.25/AI in Biz /BTL /feature_encoders.pkl